import { AiExtractionListRelationFilter } from "../aiExtraction/AiExtractionListRelationFilter";
import { AttachmentListRelationFilter } from "../attachment/AttachmentListRelationFilter";
import { AuditLogListRelationFilter } from "../auditLog/AuditLogListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { TransactionListRelationFilter } from "../transaction/TransactionListRelationFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { IntFilter } from "../../util/IntFilter";
import { InvitationListRelationFilter } from "../invitation/InvitationListRelationFilter";
import { AccountMembershipListRelationFilter } from "../accountMembership/AccountMembershipListRelationFilter";
import { UserSettingWhereUniqueInput } from "../userSetting/UserSettingWhereUniqueInput";

export type UserWhereInput = {
  aiExtractions?: AiExtractionListRelationFilter;
  attachments?: AttachmentListRelationFilter;
  auditLogs?: AuditLogListRelationFilter;
  avatarUrl?: StringNullableFilter;
  counterpartyTransactions?: TransactionListRelationFilter;
  country?: StringNullableFilter;
  createdAt?: DateTimeFilter;
  deletedAt?: DateTimeNullableFilter;
  email?: StringFilter;
  emailVerified?: BooleanFilter;
  fingerprintEnabled?: BooleanFilter;
  fullName?: StringNullableFilter;
  id?: IntFilter;
  invitationsReceived?: InvitationListRelationFilter;
  invitationsSent?: InvitationListRelationFilter;
  language?: StringFilter;
  memberships?: AccountMembershipListRelationFilter;
  passwordHash?: StringNullableFilter;
  phone?: StringNullableFilter;
  postcode?: StringNullableFilter;
  provider?: "LOCAL" | "GOOGLE" | "APPLE";
  providerId?: StringNullableFilter;
  providerToken?: StringNullableFilter;
  settings?: UserSettingWhereUniqueInput;
  transactions?: TransactionListRelationFilter;
  updatedAt?: DateTimeFilter;
  username?: StringNullableFilter;
};
