/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AttachmentService } from "../attachment.service";
import { AttachmentCreateInput } from "./AttachmentCreateInput";
import { Attachment } from "./Attachment";
import { AttachmentFindManyArgs } from "./AttachmentFindManyArgs";
import { AttachmentWhereUniqueInput } from "./AttachmentWhereUniqueInput";
import { AttachmentUpdateInput } from "./AttachmentUpdateInput";

export class AttachmentControllerBase {
  constructor(protected readonly service: AttachmentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Attachment })
  async createAttachment(
    @common.Body() data: AttachmentCreateInput
  ): Promise<Attachment> {
    return await this.service.createAttachment({
      data: {
        ...data,

        transaction: data.transaction
          ? {
              connect: data.transaction,
            }
          : undefined,

        uploadedBy: {
          connect: data.uploadedBy,
        },
      },
      select: {
        createdAt: true,
        id: true,
        kind: true,
        mimeType: true,
        sizeBytes: true,

        transaction: {
          select: {
            id: true,
          },
        },

        transcript: true,

        uploadedBy: {
          select: {
            id: true,
          },
        },

        url: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Attachment] })
  @ApiNestedQuery(AttachmentFindManyArgs)
  async attachments(@common.Req() request: Request): Promise<Attachment[]> {
    const args = plainToClass(AttachmentFindManyArgs, request.query);
    return this.service.attachments({
      ...args,
      select: {
        createdAt: true,
        id: true,
        kind: true,
        mimeType: true,
        sizeBytes: true,

        transaction: {
          select: {
            id: true,
          },
        },

        transcript: true,

        uploadedBy: {
          select: {
            id: true,
          },
        },

        url: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Attachment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async attachment(
    @common.Param() params: AttachmentWhereUniqueInput
  ): Promise<Attachment | null> {
    const result = await this.service.attachment({
      where: params,
      select: {
        createdAt: true,
        id: true,
        kind: true,
        mimeType: true,
        sizeBytes: true,

        transaction: {
          select: {
            id: true,
          },
        },

        transcript: true,

        uploadedBy: {
          select: {
            id: true,
          },
        },

        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Attachment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAttachment(
    @common.Param() params: AttachmentWhereUniqueInput,
    @common.Body() data: AttachmentUpdateInput
  ): Promise<Attachment | null> {
    try {
      return await this.service.updateAttachment({
        where: params,
        data: {
          ...data,

          transaction: data.transaction
            ? {
                connect: data.transaction,
              }
            : undefined,

          uploadedBy: {
            connect: data.uploadedBy,
          },
        },
        select: {
          createdAt: true,
          id: true,
          kind: true,
          mimeType: true,
          sizeBytes: true,

          transaction: {
            select: {
              id: true,
            },
          },

          transcript: true,

          uploadedBy: {
            select: {
              id: true,
            },
          },

          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Attachment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAttachment(
    @common.Param() params: AttachmentWhereUniqueInput
  ): Promise<Attachment | null> {
    try {
      return await this.service.deleteAttachment({
        where: params,
        select: {
          createdAt: true,
          id: true,
          kind: true,
          mimeType: true,
          sizeBytes: true,

          transaction: {
            select: {
              id: true,
            },
          },

          transcript: true,

          uploadedBy: {
            select: {
              id: true,
            },
          },

          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
