/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsInt,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  ValidateNested,
  IsBoolean,
} from "class-validator";

import { Type } from "class-transformer";
import { InvitationCreateNestedManyWithoutAccountsInput } from "./InvitationCreateNestedManyWithoutAccountsInput";
import { AccountMembershipCreateNestedManyWithoutAccountsInput } from "./AccountMembershipCreateNestedManyWithoutAccountsInput";
import { TransactionCreateNestedManyWithoutAccountsInput } from "./TransactionCreateNestedManyWithoutAccountsInput";

@InputType()
class AccountCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  balanceCents?: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  currency!: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => InvitationCreateNestedManyWithoutAccountsInput,
  })
  @ValidateNested()
  @Type(() => InvitationCreateNestedManyWithoutAccountsInput)
  @IsOptional()
  @Field(() => InvitationCreateNestedManyWithoutAccountsInput, {
    nullable: true,
  })
  invitations?: InvitationCreateNestedManyWithoutAccountsInput;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isCompany!: boolean;

  @ApiProperty({
    required: false,
    type: () => AccountMembershipCreateNestedManyWithoutAccountsInput,
  })
  @ValidateNested()
  @Type(() => AccountMembershipCreateNestedManyWithoutAccountsInput)
  @IsOptional()
  @Field(() => AccountMembershipCreateNestedManyWithoutAccountsInput, {
    nullable: true,
  })
  memberships?: AccountMembershipCreateNestedManyWithoutAccountsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  note?: string | null;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutAccountsInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutAccountsInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutAccountsInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutAccountsInput;
}

export { AccountCreateInput as AccountCreateInput };
