/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AiExtractionUpdateManyWithoutCategoriesInput } from "./AiExtractionUpdateManyWithoutCategoriesInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { CategoryUpdateManyWithoutCategoriesInput } from "./CategoryUpdateManyWithoutCategoriesInput";
import { CategoryWhereUniqueInput } from "./CategoryWhereUniqueInput";
import { TransactionUpdateManyWithoutCategoriesInput } from "./TransactionUpdateManyWithoutCategoriesInput";

@InputType()
class CategoryUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AiExtractionUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => AiExtractionUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => AiExtractionUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  aiExtractions?: AiExtractionUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => CategoryUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => CategoryUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => CategoryUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  children?: CategoryUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  icon?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isIncome?: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  parent?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  transactions?: TransactionUpdateManyWithoutCategoriesInput;
}

export { CategoryUpdateInput as CategoryUpdateInput };
