/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AiExtractionCreateNestedManyWithoutCategoriesInput } from "./AiExtractionCreateNestedManyWithoutCategoriesInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { CategoryCreateNestedManyWithoutCategoriesInput } from "./CategoryCreateNestedManyWithoutCategoriesInput";
import { CategoryWhereUniqueInput } from "./CategoryWhereUniqueInput";
import { TransactionCreateNestedManyWithoutCategoriesInput } from "./TransactionCreateNestedManyWithoutCategoriesInput";

@InputType()
class CategoryCreateInput {
  @ApiProperty({
    required: false,
    type: () => AiExtractionCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => AiExtractionCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => AiExtractionCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  aiExtractions?: AiExtractionCreateNestedManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => CategoryCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => CategoryCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => CategoryCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  children?: CategoryCreateNestedManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  icon?: string | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isIncome!: boolean;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  parent?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutCategoriesInput;
}

export { CategoryCreateInput as CategoryCreateInput };
