/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AiExtraction } from "./AiExtraction";
import { AiExtractionCountArgs } from "./AiExtractionCountArgs";
import { AiExtractionFindManyArgs } from "./AiExtractionFindManyArgs";
import { AiExtractionFindUniqueArgs } from "./AiExtractionFindUniqueArgs";
import { CreateAiExtractionArgs } from "./CreateAiExtractionArgs";
import { UpdateAiExtractionArgs } from "./UpdateAiExtractionArgs";
import { DeleteAiExtractionArgs } from "./DeleteAiExtractionArgs";
import { User } from "../../user/base/User";
import { Category } from "../../category/base/Category";
import { Transaction } from "../../transaction/base/Transaction";
import { AiExtractionService } from "../aiExtraction.service";
@graphql.Resolver(() => AiExtraction)
export class AiExtractionResolverBase {
  constructor(protected readonly service: AiExtractionService) {}

  async _aiExtractionsMeta(
    @graphql.Args() args: AiExtractionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AiExtraction])
  async aiExtractions(
    @graphql.Args() args: AiExtractionFindManyArgs
  ): Promise<AiExtraction[]> {
    return this.service.aiExtractions(args);
  }

  @graphql.Query(() => AiExtraction, { nullable: true })
  async aiExtraction(
    @graphql.Args() args: AiExtractionFindUniqueArgs
  ): Promise<AiExtraction | null> {
    const result = await this.service.aiExtraction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AiExtraction)
  async createAiExtraction(
    @graphql.Args() args: CreateAiExtractionArgs
  ): Promise<AiExtraction> {
    return await this.service.createAiExtraction({
      ...args,
      data: {
        ...args.data,

        extractedBy: args.data.extractedBy
          ? {
              connect: args.data.extractedBy,
            }
          : undefined,

        inferredCategory: args.data.inferredCategory
          ? {
              connect: args.data.inferredCategory,
            }
          : undefined,

        transaction: {
          connect: args.data.transaction,
        },
      },
    });
  }

  @graphql.Mutation(() => AiExtraction)
  async updateAiExtraction(
    @graphql.Args() args: UpdateAiExtractionArgs
  ): Promise<AiExtraction | null> {
    try {
      return await this.service.updateAiExtraction({
        ...args,
        data: {
          ...args.data,

          extractedBy: args.data.extractedBy
            ? {
                connect: args.data.extractedBy,
              }
            : undefined,

          inferredCategory: args.data.inferredCategory
            ? {
                connect: args.data.inferredCategory,
              }
            : undefined,

          transaction: {
            connect: args.data.transaction,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AiExtraction)
  async deleteAiExtraction(
    @graphql.Args() args: DeleteAiExtractionArgs
  ): Promise<AiExtraction | null> {
    try {
      return await this.service.deleteAiExtraction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "extractedBy",
  })
  async getExtractedBy(
    @graphql.Parent() parent: AiExtraction
  ): Promise<User | null> {
    const result = await this.service.getExtractedBy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Category, {
    nullable: true,
    name: "inferredCategory",
  })
  async getInferredCategory(
    @graphql.Parent() parent: AiExtraction
  ): Promise<Category | null> {
    const result = await this.service.getInferredCategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Transaction, {
    nullable: true,
    name: "transaction",
  })
  async getTransaction(
    @graphql.Parent() parent: AiExtraction
  ): Promise<Transaction | null> {
    const result = await this.service.getTransaction(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
