/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AiExtractionService } from "../aiExtraction.service";
import { AiExtractionCreateInput } from "./AiExtractionCreateInput";
import { AiExtraction } from "./AiExtraction";
import { AiExtractionFindManyArgs } from "./AiExtractionFindManyArgs";
import { AiExtractionWhereUniqueInput } from "./AiExtractionWhereUniqueInput";
import { AiExtractionUpdateInput } from "./AiExtractionUpdateInput";

export class AiExtractionControllerBase {
  constructor(protected readonly service: AiExtractionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AiExtraction })
  async createAiExtraction(
    @common.Body() data: AiExtractionCreateInput
  ): Promise<AiExtraction> {
    return await this.service.createAiExtraction({
      data: {
        ...data,

        extractedBy: data.extractedBy
          ? {
              connect: data.extractedBy,
            }
          : undefined,

        inferredCategory: data.inferredCategory
          ? {
              connect: data.inferredCategory,
            }
          : undefined,

        transaction: {
          connect: data.transaction,
        },
      },
      select: {
        actorReviewed: true,
        amount: true,
        confidenceScore: true,
        currency: true,
        description: true,
        extractedAt: true,

        extractedBy: {
          select: {
            id: true,
          },
        },

        id: true,

        inferredCategory: {
          select: {
            id: true,
          },
        },

        inferredType: true,
        meta: true,
        rawPayload: true,
        reviewerId: true,
        shopName: true,

        transaction: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AiExtraction] })
  @ApiNestedQuery(AiExtractionFindManyArgs)
  async aiExtractions(@common.Req() request: Request): Promise<AiExtraction[]> {
    const args = plainToClass(AiExtractionFindManyArgs, request.query);
    return this.service.aiExtractions({
      ...args,
      select: {
        actorReviewed: true,
        amount: true,
        confidenceScore: true,
        currency: true,
        description: true,
        extractedAt: true,

        extractedBy: {
          select: {
            id: true,
          },
        },

        id: true,

        inferredCategory: {
          select: {
            id: true,
          },
        },

        inferredType: true,
        meta: true,
        rawPayload: true,
        reviewerId: true,
        shopName: true,

        transaction: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AiExtraction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async aiExtraction(
    @common.Param() params: AiExtractionWhereUniqueInput
  ): Promise<AiExtraction | null> {
    const result = await this.service.aiExtraction({
      where: params,
      select: {
        actorReviewed: true,
        amount: true,
        confidenceScore: true,
        currency: true,
        description: true,
        extractedAt: true,

        extractedBy: {
          select: {
            id: true,
          },
        },

        id: true,

        inferredCategory: {
          select: {
            id: true,
          },
        },

        inferredType: true,
        meta: true,
        rawPayload: true,
        reviewerId: true,
        shopName: true,

        transaction: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AiExtraction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAiExtraction(
    @common.Param() params: AiExtractionWhereUniqueInput,
    @common.Body() data: AiExtractionUpdateInput
  ): Promise<AiExtraction | null> {
    try {
      return await this.service.updateAiExtraction({
        where: params,
        data: {
          ...data,

          extractedBy: data.extractedBy
            ? {
                connect: data.extractedBy,
              }
            : undefined,

          inferredCategory: data.inferredCategory
            ? {
                connect: data.inferredCategory,
              }
            : undefined,

          transaction: {
            connect: data.transaction,
          },
        },
        select: {
          actorReviewed: true,
          amount: true,
          confidenceScore: true,
          currency: true,
          description: true,
          extractedAt: true,

          extractedBy: {
            select: {
              id: true,
            },
          },

          id: true,

          inferredCategory: {
            select: {
              id: true,
            },
          },

          inferredType: true,
          meta: true,
          rawPayload: true,
          reviewerId: true,
          shopName: true,

          transaction: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AiExtraction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAiExtraction(
    @common.Param() params: AiExtractionWhereUniqueInput
  ): Promise<AiExtraction | null> {
    try {
      return await this.service.deleteAiExtraction({
        where: params,
        select: {
          actorReviewed: true,
          amount: true,
          confidenceScore: true,
          currency: true,
          description: true,
          extractedAt: true,

          extractedBy: {
            select: {
              id: true,
            },
          },

          id: true,

          inferredCategory: {
            select: {
              id: true,
            },
          },

          inferredType: true,
          meta: true,
          rawPayload: true,
          reviewerId: true,
          shopName: true,

          transaction: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
