/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  AiExtraction as PrismaAiExtraction,
  User as PrismaUser,
  Category as PrismaCategory,
  Transaction as PrismaTransaction,
} from "@prisma/client";

export class AiExtractionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AiExtractionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.aiExtraction.count(args);
  }

  async aiExtractions(
    args: Prisma.AiExtractionFindManyArgs
  ): Promise<PrismaAiExtraction[]> {
    return this.prisma.aiExtraction.findMany(args);
  }
  async aiExtraction(
    args: Prisma.AiExtractionFindUniqueArgs
  ): Promise<PrismaAiExtraction | null> {
    return this.prisma.aiExtraction.findUnique(args);
  }
  async createAiExtraction(
    args: Prisma.AiExtractionCreateArgs
  ): Promise<PrismaAiExtraction> {
    return this.prisma.aiExtraction.create(args);
  }
  async updateAiExtraction(
    args: Prisma.AiExtractionUpdateArgs
  ): Promise<PrismaAiExtraction> {
    return this.prisma.aiExtraction.update(args);
  }
  async deleteAiExtraction(
    args: Prisma.AiExtractionDeleteArgs
  ): Promise<PrismaAiExtraction> {
    return this.prisma.aiExtraction.delete(args);
  }

  async getExtractedBy(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.aiExtraction
      .findUnique({
        where: { id: parentId },
      })
      .extractedBy();
  }

  async getInferredCategory(parentId: string): Promise<PrismaCategory | null> {
    return this.prisma.aiExtraction
      .findUnique({
        where: { id: parentId },
      })
      .inferredCategory();
  }

  async getTransaction(parentId: string): Promise<PrismaTransaction | null> {
    return this.prisma.aiExtraction
      .findUnique({
        where: { id: parentId },
      })
      .transaction();
  }
}
