/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { User } from "./User";
import { UserCountArgs } from "./UserCountArgs";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserFindUniqueArgs } from "./UserFindUniqueArgs";
import { CreateUserArgs } from "./CreateUserArgs";
import { UpdateUserArgs } from "./UpdateUserArgs";
import { DeleteUserArgs } from "./DeleteUserArgs";
import { AiExtractionFindManyArgs } from "../../aiExtraction/base/AiExtractionFindManyArgs";
import { AiExtraction } from "../../aiExtraction/base/AiExtraction";
import { AttachmentFindManyArgs } from "../../attachment/base/AttachmentFindManyArgs";
import { Attachment } from "../../attachment/base/Attachment";
import { AuditLogFindManyArgs } from "../../auditLog/base/AuditLogFindManyArgs";
import { AuditLog } from "../../auditLog/base/AuditLog";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { InvitationFindManyArgs } from "../../invitation/base/InvitationFindManyArgs";
import { Invitation } from "../../invitation/base/Invitation";
import { AccountMembershipFindManyArgs } from "../../accountMembership/base/AccountMembershipFindManyArgs";
import { AccountMembership } from "../../accountMembership/base/AccountMembership";
import { UserSetting } from "../../userSetting/base/UserSetting";
import { UserService } from "../user.service";
@graphql.Resolver(() => User)
export class UserResolverBase {
  constructor(protected readonly service: UserService) {}

  async _usersMeta(
    @graphql.Args() args: UserCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [User])
  async users(@graphql.Args() args: UserFindManyArgs): Promise<User[]> {
    return this.service.users(args);
  }

  @graphql.Query(() => User, { nullable: true })
  async user(@graphql.Args() args: UserFindUniqueArgs): Promise<User | null> {
    const result = await this.service.user(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => User)
  async createUser(@graphql.Args() args: CreateUserArgs): Promise<User> {
    return await this.service.createUser({
      ...args,
      data: {
        ...args.data,

        settings: args.data.settings
          ? {
              connect: args.data.settings,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => User)
  async updateUser(@graphql.Args() args: UpdateUserArgs): Promise<User | null> {
    try {
      return await this.service.updateUser({
        ...args,
        data: {
          ...args.data,

          settings: args.data.settings
            ? {
                connect: args.data.settings,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => User)
  async deleteUser(@graphql.Args() args: DeleteUserArgs): Promise<User | null> {
    try {
      return await this.service.deleteUser(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [AiExtraction], { name: "aiExtractions" })
  async findAiExtractions(
    @graphql.Parent() parent: User,
    @graphql.Args() args: AiExtractionFindManyArgs
  ): Promise<AiExtraction[]> {
    const results = await this.service.findAiExtractions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Attachment], { name: "attachments" })
  async findAttachments(
    @graphql.Parent() parent: User,
    @graphql.Args() args: AttachmentFindManyArgs
  ): Promise<Attachment[]> {
    const results = await this.service.findAttachments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [AuditLog], { name: "auditLogs" })
  async findAuditLogs(
    @graphql.Parent() parent: User,
    @graphql.Args() args: AuditLogFindManyArgs
  ): Promise<AuditLog[]> {
    const results = await this.service.findAuditLogs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Transaction], {
    name: "counterpartyTransactions",
  })
  async findCounterpartyTransactions(
    @graphql.Parent() parent: User,
    @graphql.Args() args: TransactionFindManyArgs
  ): Promise<Transaction[]> {
    const results = await this.service.findCounterpartyTransactions(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Invitation], { name: "invitationsReceived" })
  async findInvitationsReceived(
    @graphql.Parent() parent: User,
    @graphql.Args() args: InvitationFindManyArgs
  ): Promise<Invitation[]> {
    const results = await this.service.findInvitationsReceived(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Invitation], { name: "invitationsSent" })
  async findInvitationsSent(
    @graphql.Parent() parent: User,
    @graphql.Args() args: InvitationFindManyArgs
  ): Promise<Invitation[]> {
    const results = await this.service.findInvitationsSent(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [AccountMembership], { name: "memberships" })
  async findMemberships(
    @graphql.Parent() parent: User,
    @graphql.Args() args: AccountMembershipFindManyArgs
  ): Promise<AccountMembership[]> {
    const results = await this.service.findMemberships(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Transaction], { name: "transactions" })
  async findTransactions(
    @graphql.Parent() parent: User,
    @graphql.Args() args: TransactionFindManyArgs
  ): Promise<Transaction[]> {
    const results = await this.service.findTransactions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => UserSetting, {
    nullable: true,
    name: "settings",
  })
  async getSettings(
    @graphql.Parent() parent: User
  ): Promise<UserSetting | null> {
    const result = await this.service.getSettings(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
