/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AiExtractionListRelationFilter } from "../../aiExtraction/base/AiExtractionListRelationFilter";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { AttachmentListRelationFilter } from "../../attachment/base/AttachmentListRelationFilter";
import { AuditLogListRelationFilter } from "../../auditLog/base/AuditLogListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { TransactionListRelationFilter } from "../../transaction/base/TransactionListRelationFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { IntFilter } from "../../util/IntFilter";
import { InvitationListRelationFilter } from "../../invitation/base/InvitationListRelationFilter";
import { AccountMembershipListRelationFilter } from "../../accountMembership/base/AccountMembershipListRelationFilter";
import { EnumUserProvider } from "./EnumUserProvider";
import { UserSettingWhereUniqueInput } from "../../userSetting/base/UserSettingWhereUniqueInput";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: () => AiExtractionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AiExtractionListRelationFilter)
  @IsOptional()
  @Field(() => AiExtractionListRelationFilter, {
    nullable: true,
  })
  aiExtractions?: AiExtractionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AttachmentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AttachmentListRelationFilter)
  @IsOptional()
  @Field(() => AttachmentListRelationFilter, {
    nullable: true,
  })
  attachments?: AttachmentListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AuditLogListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AuditLogListRelationFilter)
  @IsOptional()
  @Field(() => AuditLogListRelationFilter, {
    nullable: true,
  })
  auditLogs?: AuditLogListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  avatarUrl?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TransactionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TransactionListRelationFilter)
  @IsOptional()
  @Field(() => TransactionListRelationFilter, {
    nullable: true,
  })
  counterpartyTransactions?: TransactionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  country?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  deletedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  email?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanFilter,
  })
  @Type(() => BooleanFilter)
  @IsOptional()
  @Field(() => BooleanFilter, {
    nullable: true,
  })
  emailVerified?: BooleanFilter;

  @ApiProperty({
    required: false,
    type: BooleanFilter,
  })
  @Type(() => BooleanFilter)
  @IsOptional()
  @Field(() => BooleanFilter, {
    nullable: true,
  })
  fingerprintEnabled?: BooleanFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  fullName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: () => InvitationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => InvitationListRelationFilter)
  @IsOptional()
  @Field(() => InvitationListRelationFilter, {
    nullable: true,
  })
  invitationsReceived?: InvitationListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => InvitationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => InvitationListRelationFilter)
  @IsOptional()
  @Field(() => InvitationListRelationFilter, {
    nullable: true,
  })
  invitationsSent?: InvitationListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  language?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => AccountMembershipListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AccountMembershipListRelationFilter)
  @IsOptional()
  @Field(() => AccountMembershipListRelationFilter, {
    nullable: true,
  })
  memberships?: AccountMembershipListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  passwordHash?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  phone?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  postcode?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumUserProvider,
  })
  @IsEnum(EnumUserProvider)
  @IsOptional()
  @Field(() => EnumUserProvider, {
    nullable: true,
  })
  provider?: "LOCAL" | "GOOGLE" | "APPLE";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  providerId?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  providerToken?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserSettingWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserSettingWhereUniqueInput)
  @IsOptional()
  @Field(() => UserSettingWhereUniqueInput, {
    nullable: true,
  })
  settings?: UserSettingWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => TransactionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TransactionListRelationFilter)
  @IsOptional()
  @Field(() => TransactionListRelationFilter, {
    nullable: true,
  })
  transactions?: TransactionListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  username?: StringNullableFilter;
}

export { UserWhereInput as UserWhereInput };
