/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AiExtraction } from "../../aiExtraction/base/AiExtraction";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  IsBoolean,
  IsInt,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { Attachment } from "../../attachment/base/Attachment";
import { AuditLog } from "../../auditLog/base/AuditLog";
import { Transaction } from "../../transaction/base/Transaction";
import { Invitation } from "../../invitation/base/Invitation";
import { AccountMembership } from "../../accountMembership/base/AccountMembership";
import { EnumUserProvider } from "./EnumUserProvider";
import { UserSetting } from "../../userSetting/base/UserSetting";

@ObjectType()
class User {
  @ApiProperty({
    required: false,
    type: () => [AiExtraction],
  })
  @ValidateNested()
  @Type(() => AiExtraction)
  @IsOptional()
  aiExtractions?: Array<AiExtraction>;

  @ApiProperty({
    required: false,
    type: () => [Attachment],
  })
  @ValidateNested()
  @Type(() => Attachment)
  @IsOptional()
  attachments?: Array<Attachment>;

  @ApiProperty({
    required: false,
    type: () => [AuditLog],
  })
  @ValidateNested()
  @Type(() => AuditLog)
  @IsOptional()
  auditLogs?: Array<AuditLog>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  avatarUrl!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Transaction],
  })
  @ValidateNested()
  @Type(() => Transaction)
  @IsOptional()
  counterpartyTransactions?: Array<Transaction>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt!: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  emailVerified!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  fingerprintEnabled!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName!: string | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: false,
    type: () => [Invitation],
  })
  @ValidateNested()
  @Type(() => Invitation)
  @IsOptional()
  invitationsReceived?: Array<Invitation>;

  @ApiProperty({
    required: false,
    type: () => [Invitation],
  })
  @ValidateNested()
  @Type(() => Invitation)
  @IsOptional()
  invitationsSent?: Array<Invitation>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  language!: string;

  @ApiProperty({
    required: false,
    type: () => [AccountMembership],
  })
  @ValidateNested()
  @Type(() => AccountMembership)
  @IsOptional()
  memberships?: Array<AccountMembership>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  passwordHash!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  postcode!: string | null;

  @ApiProperty({
    required: true,
    enum: EnumUserProvider,
  })
  @IsEnum(EnumUserProvider)
  @Field(() => EnumUserProvider, {
    nullable: true,
  })
  provider?: "LOCAL" | "GOOGLE" | "APPLE";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  providerId!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  providerToken!: string | null;

  @ApiProperty({
    required: false,
    type: () => UserSetting,
  })
  @ValidateNested()
  @Type(() => UserSetting)
  @IsOptional()
  settings?: UserSetting | null;

  @ApiProperty({
    required: false,
    type: () => [Transaction],
  })
  @ValidateNested()
  @Type(() => Transaction)
  @IsOptional()
  transactions?: Array<Transaction>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username!: string | null;
}

export { User as User };
