/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { AiExtractionFindManyArgs } from "../../aiExtraction/base/AiExtractionFindManyArgs";
import { AiExtraction } from "../../aiExtraction/base/AiExtraction";
import { AiExtractionWhereUniqueInput } from "../../aiExtraction/base/AiExtractionWhereUniqueInput";
import { AttachmentFindManyArgs } from "../../attachment/base/AttachmentFindManyArgs";
import { Attachment } from "../../attachment/base/Attachment";
import { AttachmentWhereUniqueInput } from "../../attachment/base/AttachmentWhereUniqueInput";
import { AuditLogFindManyArgs } from "../../auditLog/base/AuditLogFindManyArgs";
import { AuditLog } from "../../auditLog/base/AuditLog";
import { AuditLogWhereUniqueInput } from "../../auditLog/base/AuditLogWhereUniqueInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";
import { InvitationFindManyArgs } from "../../invitation/base/InvitationFindManyArgs";
import { Invitation } from "../../invitation/base/Invitation";
import { InvitationWhereUniqueInput } from "../../invitation/base/InvitationWhereUniqueInput";
import { AccountMembershipFindManyArgs } from "../../accountMembership/base/AccountMembershipFindManyArgs";
import { AccountMembership } from "../../accountMembership/base/AccountMembership";
import { AccountMembershipWhereUniqueInput } from "../../accountMembership/base/AccountMembershipWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: {
        ...data,

        settings: data.settings
          ? {
              connect: data.settings,
            }
          : undefined,
      },
      select: {
        avatarUrl: true,
        country: true,
        createdAt: true,
        deletedAt: true,
        email: true,
        emailVerified: true,
        fingerprintEnabled: true,
        fullName: true,
        id: true,
        language: true,
        passwordHash: true,
        phone: true,
        postcode: true,
        provider: true,
        providerId: true,
        providerToken: true,

        settings: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        avatarUrl: true,
        country: true,
        createdAt: true,
        deletedAt: true,
        email: true,
        emailVerified: true,
        fingerprintEnabled: true,
        fullName: true,
        id: true,
        language: true,
        passwordHash: true,
        phone: true,
        postcode: true,
        provider: true,
        providerId: true,
        providerToken: true,

        settings: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        avatarUrl: true,
        country: true,
        createdAt: true,
        deletedAt: true,
        email: true,
        emailVerified: true,
        fingerprintEnabled: true,
        fullName: true,
        id: true,
        language: true,
        passwordHash: true,
        phone: true,
        postcode: true,
        provider: true,
        providerId: true,
        providerToken: true,

        settings: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: {
          ...data,

          settings: data.settings
            ? {
                connect: data.settings,
              }
            : undefined,
        },
        select: {
          avatarUrl: true,
          country: true,
          createdAt: true,
          deletedAt: true,
          email: true,
          emailVerified: true,
          fingerprintEnabled: true,
          fullName: true,
          id: true,
          language: true,
          passwordHash: true,
          phone: true,
          postcode: true,
          provider: true,
          providerId: true,
          providerToken: true,

          settings: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          avatarUrl: true,
          country: true,
          createdAt: true,
          deletedAt: true,
          email: true,
          emailVerified: true,
          fingerprintEnabled: true,
          fullName: true,
          id: true,
          language: true,
          passwordHash: true,
          phone: true,
          postcode: true,
          provider: true,
          providerId: true,
          providerToken: true,

          settings: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/aiExtractions")
  @ApiNestedQuery(AiExtractionFindManyArgs)
  async findAiExtractions(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<AiExtraction[]> {
    const query = plainToClass(AiExtractionFindManyArgs, request.query);
    const results = await this.service.findAiExtractions(params.id, {
      ...query,
      select: {
        actorReviewed: true,
        amount: true,
        confidenceScore: true,
        currency: true,
        description: true,
        extractedAt: true,

        extractedBy: {
          select: {
            id: true,
          },
        },

        id: true,

        inferredCategory: {
          select: {
            id: true,
          },
        },

        inferredType: true,
        meta: true,
        rawPayload: true,
        reviewerId: true,
        shopName: true,

        transaction: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/aiExtractions")
  async connectAiExtractions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AiExtractionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiExtractions: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/aiExtractions")
  async updateAiExtractions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AiExtractionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiExtractions: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/aiExtractions")
  async disconnectAiExtractions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AiExtractionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiExtractions: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/attachments")
  @ApiNestedQuery(AttachmentFindManyArgs)
  async findAttachments(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Attachment[]> {
    const query = plainToClass(AttachmentFindManyArgs, request.query);
    const results = await this.service.findAttachments(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        kind: true,
        mimeType: true,
        sizeBytes: true,

        transaction: {
          select: {
            id: true,
          },
        },

        transcript: true,

        uploadedBy: {
          select: {
            id: true,
          },
        },

        url: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/attachments")
  async connectAttachments(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AttachmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attachments: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/attachments")
  async updateAttachments(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AttachmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attachments: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/attachments")
  async disconnectAttachments(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AttachmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attachments: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/auditLogs")
  @ApiNestedQuery(AuditLogFindManyArgs)
  async findAuditLogs(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<AuditLog[]> {
    const query = plainToClass(AuditLogFindManyArgs, request.query);
    const results = await this.service.findAuditLogs(params.id, {
      ...query,
      select: {
        action: true,
        createdAt: true,
        id: true,
        ipAddress: true,
        payload: true,
        resourceId: true,
        resourceType: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/auditLogs")
  async connectAuditLogs(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuditLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auditLogs: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/auditLogs")
  async updateAuditLogs(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuditLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auditLogs: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/auditLogs")
  async disconnectAuditLogs(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuditLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auditLogs: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/counterpartyTransactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  async findCounterpartyTransactions(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findCounterpartyTransactions(params.id, {
      ...query,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        aiExtraction: {
          select: {
            id: true,
          },
        },

        amount: true,

        category: {
          select: {
            id: true,
          },
        },

        counterpartyName: true,

        counterpartyUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        currency: true,
        dateOccurred: true,
        deletedAt: true,
        description: true,
        dueDate: true,
        externalRef: true,
        id: true,
        isRecurring: true,
        meta: true,
        paidAt: true,

        recordedBy: {
          select: {
            id: true,
          },
        },

        recurrenceRule: true,
        status: true,
        title: true,
        type: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/counterpartyTransactions")
  async connectCounterpartyTransactions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      counterpartyTransactions: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/counterpartyTransactions")
  async updateCounterpartyTransactions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      counterpartyTransactions: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/counterpartyTransactions")
  async disconnectCounterpartyTransactions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      counterpartyTransactions: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/invitationsReceived")
  @ApiNestedQuery(InvitationFindManyArgs)
  async findInvitationsReceived(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Invitation[]> {
    const query = plainToClass(InvitationFindManyArgs, request.query);
    const results = await this.service.findInvitationsReceived(params.id, {
      ...query,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expiresAt: true,
        id: true,

        invitee: {
          select: {
            id: true,
          },
        },

        inviteeEmail: true,

        inviter: {
          select: {
            id: true,
          },
        },

        status: true,
        token: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/invitationsReceived")
  async connectInvitationsReceived(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: InvitationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invitationsReceived: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/invitationsReceived")
  async updateInvitationsReceived(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: InvitationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invitationsReceived: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/invitationsReceived")
  async disconnectInvitationsReceived(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: InvitationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invitationsReceived: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/invitationsSent")
  @ApiNestedQuery(InvitationFindManyArgs)
  async findInvitationsSent(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Invitation[]> {
    const query = plainToClass(InvitationFindManyArgs, request.query);
    const results = await this.service.findInvitationsSent(params.id, {
      ...query,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expiresAt: true,
        id: true,

        invitee: {
          select: {
            id: true,
          },
        },

        inviteeEmail: true,

        inviter: {
          select: {
            id: true,
          },
        },

        status: true,
        token: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/invitationsSent")
  async connectInvitationsSent(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: InvitationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invitationsSent: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/invitationsSent")
  async updateInvitationsSent(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: InvitationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invitationsSent: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/invitationsSent")
  async disconnectInvitationsSent(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: InvitationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invitationsSent: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/memberships")
  @ApiNestedQuery(AccountMembershipFindManyArgs)
  async findMemberships(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<AccountMembership[]> {
    const query = plainToClass(AccountMembershipFindManyArgs, request.query);
    const results = await this.service.findMemberships(params.id, {
      ...query,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        id: true,
        isActive: true,
        joinedAt: true,
        role: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/memberships")
  async connectMemberships(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AccountMembershipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      memberships: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/memberships")
  async updateMemberships(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AccountMembershipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      memberships: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/memberships")
  async disconnectMemberships(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AccountMembershipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      memberships: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        aiExtraction: {
          select: {
            id: true,
          },
        },

        amount: true,

        category: {
          select: {
            id: true,
          },
        },

        counterpartyName: true,

        counterpartyUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        currency: true,
        dateOccurred: true,
        deletedAt: true,
        description: true,
        dueDate: true,
        externalRef: true,
        id: true,
        isRecurring: true,
        meta: true,
        paidAt: true,

        recordedBy: {
          select: {
            id: true,
          },
        },

        recurrenceRule: true,
        status: true,
        title: true,
        type: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  async connectTransactions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  async updateTransactions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  async disconnectTransactions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
