/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AiExtractionCreateNestedManyWithoutUsersInput } from "./AiExtractionCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  IsBoolean,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { AttachmentCreateNestedManyWithoutUsersInput } from "./AttachmentCreateNestedManyWithoutUsersInput";
import { AuditLogCreateNestedManyWithoutUsersInput } from "./AuditLogCreateNestedManyWithoutUsersInput";
import { TransactionCreateNestedManyWithoutUsersInput } from "./TransactionCreateNestedManyWithoutUsersInput";
import { InvitationCreateNestedManyWithoutUsersInput } from "./InvitationCreateNestedManyWithoutUsersInput";
import { AccountMembershipCreateNestedManyWithoutUsersInput } from "./AccountMembershipCreateNestedManyWithoutUsersInput";
import { EnumUserProvider } from "./EnumUserProvider";
import { UserSettingWhereUniqueInput } from "../../userSetting/base/UserSettingWhereUniqueInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => AiExtractionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AiExtractionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AiExtractionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  aiExtractions?: AiExtractionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => AttachmentCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AttachmentCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AttachmentCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  attachments?: AttachmentCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => AuditLogCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AuditLogCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AuditLogCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  auditLogs?: AuditLogCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  avatarUrl?: string | null;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  counterpartyTransactions?: TransactionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt?: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  emailVerified!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  fingerprintEnabled!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvitationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => InvitationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => InvitationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  invitationsReceived?: InvitationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => InvitationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => InvitationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => InvitationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  invitationsSent?: InvitationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  language!: string;

  @ApiProperty({
    required: false,
    type: () => AccountMembershipCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AccountMembershipCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AccountMembershipCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  memberships?: AccountMembershipCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  passwordHash?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  postcode?: string | null;

  @ApiProperty({
    required: true,
    enum: EnumUserProvider,
  })
  @IsEnum(EnumUserProvider)
  @Field(() => EnumUserProvider)
  provider!: "LOCAL" | "GOOGLE" | "APPLE";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  providerId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  providerToken?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserSettingWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserSettingWhereUniqueInput)
  @IsOptional()
  @Field(() => UserSettingWhereUniqueInput, {
    nullable: true,
  })
  settings?: UserSettingWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { UserCreateInput as UserCreateInput };
