/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  User as PrismaUser,
  AiExtraction as PrismaAiExtraction,
  Attachment as PrismaAttachment,
  AuditLog as PrismaAuditLog,
  Transaction as PrismaTransaction,
  Invitation as PrismaInvitation,
  AccountMembership as PrismaAccountMembership,
  UserSetting as PrismaUserSetting,
} from "@prisma/client";

export class UserServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.UserCountArgs, "select">): Promise<number> {
    return this.prisma.user.count(args);
  }

  async users(args: Prisma.UserFindManyArgs): Promise<PrismaUser[]> {
    return this.prisma.user.findMany(args);
  }
  async user(args: Prisma.UserFindUniqueArgs): Promise<PrismaUser | null> {
    return this.prisma.user.findUnique(args);
  }
  async createUser(args: Prisma.UserCreateArgs): Promise<PrismaUser> {
    return this.prisma.user.create(args);
  }
  async updateUser(args: Prisma.UserUpdateArgs): Promise<PrismaUser> {
    return this.prisma.user.update(args);
  }
  async deleteUser(args: Prisma.UserDeleteArgs): Promise<PrismaUser> {
    return this.prisma.user.delete(args);
  }

  async findAiExtractions(
    parentId: number,
    args: Prisma.AiExtractionFindManyArgs
  ): Promise<PrismaAiExtraction[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .aiExtractions(args);
  }

  async findAttachments(
    parentId: number,
    args: Prisma.AttachmentFindManyArgs
  ): Promise<PrismaAttachment[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .attachments(args);
  }

  async findAuditLogs(
    parentId: number,
    args: Prisma.AuditLogFindManyArgs
  ): Promise<PrismaAuditLog[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .auditLogs(args);
  }

  async findCounterpartyTransactions(
    parentId: number,
    args: Prisma.TransactionFindManyArgs
  ): Promise<PrismaTransaction[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .counterpartyTransactions(args);
  }

  async findInvitationsReceived(
    parentId: number,
    args: Prisma.InvitationFindManyArgs
  ): Promise<PrismaInvitation[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .invitationsReceived(args);
  }

  async findInvitationsSent(
    parentId: number,
    args: Prisma.InvitationFindManyArgs
  ): Promise<PrismaInvitation[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .invitationsSent(args);
  }

  async findMemberships(
    parentId: number,
    args: Prisma.AccountMembershipFindManyArgs
  ): Promise<PrismaAccountMembership[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .memberships(args);
  }

  async findTransactions(
    parentId: number,
    args: Prisma.TransactionFindManyArgs
  ): Promise<PrismaTransaction[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .transactions(args);
  }

  async getSettings(parentId: number): Promise<PrismaUserSetting | null> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .settings();
  }
}
