/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AiExtractionUpdateManyWithoutUsersInput } from "./AiExtractionUpdateManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  IsBoolean,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { AttachmentUpdateManyWithoutUsersInput } from "./AttachmentUpdateManyWithoutUsersInput";
import { AuditLogUpdateManyWithoutUsersInput } from "./AuditLogUpdateManyWithoutUsersInput";
import { TransactionUpdateManyWithoutUsersInput } from "./TransactionUpdateManyWithoutUsersInput";
import { InvitationUpdateManyWithoutUsersInput } from "./InvitationUpdateManyWithoutUsersInput";
import { AccountMembershipUpdateManyWithoutUsersInput } from "./AccountMembershipUpdateManyWithoutUsersInput";
import { EnumUserProvider } from "./EnumUserProvider";
import { UserSettingWhereUniqueInput } from "../../userSetting/base/UserSettingWhereUniqueInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AiExtractionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AiExtractionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AiExtractionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  aiExtractions?: AiExtractionUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => AttachmentUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AttachmentUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AttachmentUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  attachments?: AttachmentUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => AuditLogUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AuditLogUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AuditLogUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  auditLogs?: AuditLogUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  avatarUrl?: string | null;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  counterpartyTransactions?: TransactionUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  emailVerified?: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  fingerprintEnabled?: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvitationUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => InvitationUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => InvitationUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  invitationsReceived?: InvitationUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => InvitationUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => InvitationUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => InvitationUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  invitationsSent?: InvitationUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  language?: string;

  @ApiProperty({
    required: false,
    type: () => AccountMembershipUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AccountMembershipUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AccountMembershipUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  memberships?: AccountMembershipUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  passwordHash?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  postcode?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumUserProvider,
  })
  @IsEnum(EnumUserProvider)
  @IsOptional()
  @Field(() => EnumUserProvider, {
    nullable: true,
  })
  provider?: "LOCAL" | "GOOGLE" | "APPLE";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  providerId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  providerToken?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserSettingWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserSettingWhereUniqueInput)
  @IsOptional()
  @Field(() => UserSettingWhereUniqueInput, {
    nullable: true,
  })
  settings?: UserSettingWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  transactions?: TransactionUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { UserUpdateInput as UserUpdateInput };
