/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  UserSetting as PrismaUserSetting,
  User as PrismaUser,
} from "@prisma/client";

export class UserSettingServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.UserSettingCountArgs, "select">
  ): Promise<number> {
    return this.prisma.userSetting.count(args);
  }

  async userSettings(
    args: Prisma.UserSettingFindManyArgs
  ): Promise<PrismaUserSetting[]> {
    return this.prisma.userSetting.findMany(args);
  }
  async userSetting(
    args: Prisma.UserSettingFindUniqueArgs
  ): Promise<PrismaUserSetting | null> {
    return this.prisma.userSetting.findUnique(args);
  }
  async createUserSetting(
    args: Prisma.UserSettingCreateArgs
  ): Promise<PrismaUserSetting> {
    return this.prisma.userSetting.create(args);
  }
  async updateUserSetting(
    args: Prisma.UserSettingUpdateArgs
  ): Promise<PrismaUserSetting> {
    return this.prisma.userSetting.update(args);
  }
  async deleteUserSetting(
    args: Prisma.UserSettingDeleteArgs
  ): Promise<PrismaUserSetting> {
    return this.prisma.userSetting.delete(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.userSetting
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
