/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserSettingService } from "../userSetting.service";
import { UserSettingCreateInput } from "./UserSettingCreateInput";
import { UserSetting } from "./UserSetting";
import { UserSettingFindManyArgs } from "./UserSettingFindManyArgs";
import { UserSettingWhereUniqueInput } from "./UserSettingWhereUniqueInput";
import { UserSettingUpdateInput } from "./UserSettingUpdateInput";

export class UserSettingControllerBase {
  constructor(protected readonly service: UserSettingService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserSetting })
  async createUserSetting(
    @common.Body() data: UserSettingCreateInput
  ): Promise<UserSetting> {
    return await this.service.createUserSetting({
      data: {
        ...data,

        user: {
          connect: data.user,
        },
      },
      select: {
        createdAt: true,
        defaultAccountId: true,
        enableBiometrics: true,
        id: true,
        language: true,
        timeZone: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [UserSetting] })
  @ApiNestedQuery(UserSettingFindManyArgs)
  async userSettings(@common.Req() request: Request): Promise<UserSetting[]> {
    const args = plainToClass(UserSettingFindManyArgs, request.query);
    return this.service.userSettings({
      ...args,
      select: {
        createdAt: true,
        defaultAccountId: true,
        enableBiometrics: true,
        id: true,
        language: true,
        timeZone: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async userSetting(
    @common.Param() params: UserSettingWhereUniqueInput
  ): Promise<UserSetting | null> {
    const result = await this.service.userSetting({
      where: params,
      select: {
        createdAt: true,
        defaultAccountId: true,
        enableBiometrics: true,
        id: true,
        language: true,
        timeZone: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUserSetting(
    @common.Param() params: UserSettingWhereUniqueInput,
    @common.Body() data: UserSettingUpdateInput
  ): Promise<UserSetting | null> {
    try {
      return await this.service.updateUserSetting({
        where: params,
        data: {
          ...data,

          user: {
            connect: data.user,
          },
        },
        select: {
          createdAt: true,
          defaultAccountId: true,
          enableBiometrics: true,
          id: true,
          language: true,
          timeZone: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUserSetting(
    @common.Param() params: UserSettingWhereUniqueInput
  ): Promise<UserSetting | null> {
    try {
      return await this.service.deleteUserSetting({
        where: params,
        select: {
          createdAt: true,
          defaultAccountId: true,
          enableBiometrics: true,
          id: true,
          language: true,
          timeZone: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
