/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserSetting } from "./UserSetting";
import { UserSettingCountArgs } from "./UserSettingCountArgs";
import { UserSettingFindManyArgs } from "./UserSettingFindManyArgs";
import { UserSettingFindUniqueArgs } from "./UserSettingFindUniqueArgs";
import { CreateUserSettingArgs } from "./CreateUserSettingArgs";
import { UpdateUserSettingArgs } from "./UpdateUserSettingArgs";
import { DeleteUserSettingArgs } from "./DeleteUserSettingArgs";
import { User } from "../../user/base/User";
import { UserSettingService } from "../userSetting.service";
@graphql.Resolver(() => UserSetting)
export class UserSettingResolverBase {
  constructor(protected readonly service: UserSettingService) {}

  async _userSettingsMeta(
    @graphql.Args() args: UserSettingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserSetting])
  async userSettings(
    @graphql.Args() args: UserSettingFindManyArgs
  ): Promise<UserSetting[]> {
    return this.service.userSettings(args);
  }

  @graphql.Query(() => UserSetting, { nullable: true })
  async userSetting(
    @graphql.Args() args: UserSettingFindUniqueArgs
  ): Promise<UserSetting | null> {
    const result = await this.service.userSetting(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserSetting)
  async createUserSetting(
    @graphql.Args() args: CreateUserSettingArgs
  ): Promise<UserSetting> {
    return await this.service.createUserSetting({
      ...args,
      data: {
        ...args.data,

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @graphql.Mutation(() => UserSetting)
  async updateUserSetting(
    @graphql.Args() args: UpdateUserSettingArgs
  ): Promise<UserSetting | null> {
    try {
      return await this.service.updateUserSetting({
        ...args,
        data: {
          ...args.data,

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserSetting)
  async deleteUserSetting(
    @graphql.Args() args: DeleteUserSettingArgs
  ): Promise<UserSetting | null> {
    try {
      return await this.service.deleteUserSetting(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: UserSetting): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
