import { AccountWhereUniqueInput } from "../account/AccountWhereUniqueInput";
import { AiExtractionWhereUniqueInput } from "../aiExtraction/AiExtractionWhereUniqueInput";
import { DecimalFilter } from "../../util/DecimalFilter";
import { AttachmentListRelationFilter } from "../attachment/AttachmentListRelationFilter";
import { CategoryWhereUniqueInput } from "../category/CategoryWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringFilter } from "../../util/StringFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { JsonFilter } from "../../util/JsonFilter";

export type TransactionWhereInput = {
  account?: AccountWhereUniqueInput;
  aiExtraction?: AiExtractionWhereUniqueInput;
  amount?: DecimalFilter;
  attachments?: AttachmentListRelationFilter;
  category?: CategoryWhereUniqueInput;
  counterpartyName?: StringNullableFilter;
  counterpartyUser?: UserWhereUniqueInput;
  createdAt?: DateTimeFilter;
  currency?: StringFilter;
  dateOccurred?: DateTimeFilter;
  deletedAt?: DateTimeNullableFilter;
  description?: StringNullableFilter;
  dueDate?: DateTimeNullableFilter;
  externalRef?: StringNullableFilter;
  id?: StringFilter;
  isRecurring?: BooleanFilter;
  meta?: JsonFilter;
  paidAt?: DateTimeNullableFilter;
  recordedBy?: UserWhereUniqueInput;
  recurrenceRule?: StringNullableFilter;
  status?: "DRAFT" | "CONFIRMED" | "PAID" | "RECEIVED" | "CANCELLED";
  title?: StringFilter;
  type?: "EXPENSE" | "INCOME" | "ACCOUNT_RECEIVABLE" | "ACCOUNT_PAYABLE";
  updatedAt?: DateTimeFilter;
};
