/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AccountMembershipService } from "../accountMembership.service";
import { AccountMembershipCreateInput } from "./AccountMembershipCreateInput";
import { AccountMembership } from "./AccountMembership";
import { AccountMembershipFindManyArgs } from "./AccountMembershipFindManyArgs";
import { AccountMembershipWhereUniqueInput } from "./AccountMembershipWhereUniqueInput";
import { AccountMembershipUpdateInput } from "./AccountMembershipUpdateInput";

export class AccountMembershipControllerBase {
  constructor(protected readonly service: AccountMembershipService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AccountMembership })
  async createAccountMembership(
    @common.Body() data: AccountMembershipCreateInput
  ): Promise<AccountMembership> {
    return await this.service.createAccountMembership({
      data: {
        ...data,

        account: {
          connect: data.account,
        },

        user: {
          connect: data.user,
        },
      },
      select: {
        account: {
          select: {
            id: true,
          },
        },

        id: true,
        isActive: true,
        joinedAt: true,
        role: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AccountMembership] })
  @ApiNestedQuery(AccountMembershipFindManyArgs)
  async accountMemberships(
    @common.Req() request: Request
  ): Promise<AccountMembership[]> {
    const args = plainToClass(AccountMembershipFindManyArgs, request.query);
    return this.service.accountMemberships({
      ...args,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        id: true,
        isActive: true,
        joinedAt: true,
        role: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AccountMembership })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async accountMembership(
    @common.Param() params: AccountMembershipWhereUniqueInput
  ): Promise<AccountMembership | null> {
    const result = await this.service.accountMembership({
      where: params,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        id: true,
        isActive: true,
        joinedAt: true,
        role: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AccountMembership })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAccountMembership(
    @common.Param() params: AccountMembershipWhereUniqueInput,
    @common.Body() data: AccountMembershipUpdateInput
  ): Promise<AccountMembership | null> {
    try {
      return await this.service.updateAccountMembership({
        where: params,
        data: {
          ...data,

          account: {
            connect: data.account,
          },

          user: {
            connect: data.user,
          },
        },
        select: {
          account: {
            select: {
              id: true,
            },
          },

          id: true,
          isActive: true,
          joinedAt: true,
          role: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AccountMembership })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAccountMembership(
    @common.Param() params: AccountMembershipWhereUniqueInput
  ): Promise<AccountMembership | null> {
    try {
      return await this.service.deleteAccountMembership({
        where: params,
        select: {
          account: {
            select: {
              id: true,
            },
          },

          id: true,
          isActive: true,
          joinedAt: true,
          role: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
