/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  AccountMembership as PrismaAccountMembership,
  Account as PrismaAccount,
  User as PrismaUser,
} from "@prisma/client";

export class AccountMembershipServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AccountMembershipCountArgs, "select">
  ): Promise<number> {
    return this.prisma.accountMembership.count(args);
  }

  async accountMemberships(
    args: Prisma.AccountMembershipFindManyArgs
  ): Promise<PrismaAccountMembership[]> {
    return this.prisma.accountMembership.findMany(args);
  }
  async accountMembership(
    args: Prisma.AccountMembershipFindUniqueArgs
  ): Promise<PrismaAccountMembership | null> {
    return this.prisma.accountMembership.findUnique(args);
  }
  async createAccountMembership(
    args: Prisma.AccountMembershipCreateArgs
  ): Promise<PrismaAccountMembership> {
    return this.prisma.accountMembership.create(args);
  }
  async updateAccountMembership(
    args: Prisma.AccountMembershipUpdateArgs
  ): Promise<PrismaAccountMembership> {
    return this.prisma.accountMembership.update(args);
  }
  async deleteAccountMembership(
    args: Prisma.AccountMembershipDeleteArgs
  ): Promise<PrismaAccountMembership> {
    return this.prisma.accountMembership.delete(args);
  }

  async getAccount(parentId: string): Promise<PrismaAccount | null> {
    return this.prisma.accountMembership
      .findUnique({
        where: { id: parentId },
      })
      .account();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.accountMembership
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
