/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AccountMembership } from "./AccountMembership";
import { AccountMembershipCountArgs } from "./AccountMembershipCountArgs";
import { AccountMembershipFindManyArgs } from "./AccountMembershipFindManyArgs";
import { AccountMembershipFindUniqueArgs } from "./AccountMembershipFindUniqueArgs";
import { CreateAccountMembershipArgs } from "./CreateAccountMembershipArgs";
import { UpdateAccountMembershipArgs } from "./UpdateAccountMembershipArgs";
import { DeleteAccountMembershipArgs } from "./DeleteAccountMembershipArgs";
import { Account } from "../../account/base/Account";
import { User } from "../../user/base/User";
import { AccountMembershipService } from "../accountMembership.service";
@graphql.Resolver(() => AccountMembership)
export class AccountMembershipResolverBase {
  constructor(protected readonly service: AccountMembershipService) {}

  async _accountMembershipsMeta(
    @graphql.Args() args: AccountMembershipCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AccountMembership])
  async accountMemberships(
    @graphql.Args() args: AccountMembershipFindManyArgs
  ): Promise<AccountMembership[]> {
    return this.service.accountMemberships(args);
  }

  @graphql.Query(() => AccountMembership, { nullable: true })
  async accountMembership(
    @graphql.Args() args: AccountMembershipFindUniqueArgs
  ): Promise<AccountMembership | null> {
    const result = await this.service.accountMembership(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AccountMembership)
  async createAccountMembership(
    @graphql.Args() args: CreateAccountMembershipArgs
  ): Promise<AccountMembership> {
    return await this.service.createAccountMembership({
      ...args,
      data: {
        ...args.data,

        account: {
          connect: args.data.account,
        },

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @graphql.Mutation(() => AccountMembership)
  async updateAccountMembership(
    @graphql.Args() args: UpdateAccountMembershipArgs
  ): Promise<AccountMembership | null> {
    try {
      return await this.service.updateAccountMembership({
        ...args,
        data: {
          ...args.data,

          account: {
            connect: args.data.account,
          },

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AccountMembership)
  async deleteAccountMembership(
    @graphql.Args() args: DeleteAccountMembershipArgs
  ): Promise<AccountMembership | null> {
    try {
      return await this.service.deleteAccountMembership(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Account, {
    nullable: true,
    name: "account",
  })
  async getAccount(
    @graphql.Parent() parent: AccountMembership
  ): Promise<Account | null> {
    const result = await this.service.getAccount(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(
    @graphql.Parent() parent: AccountMembership
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
