/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Invitation } from "./Invitation";
import { InvitationCountArgs } from "./InvitationCountArgs";
import { InvitationFindManyArgs } from "./InvitationFindManyArgs";
import { InvitationFindUniqueArgs } from "./InvitationFindUniqueArgs";
import { CreateInvitationArgs } from "./CreateInvitationArgs";
import { UpdateInvitationArgs } from "./UpdateInvitationArgs";
import { DeleteInvitationArgs } from "./DeleteInvitationArgs";
import { Account } from "../../account/base/Account";
import { User } from "../../user/base/User";
import { InvitationService } from "../invitation.service";
@graphql.Resolver(() => Invitation)
export class InvitationResolverBase {
  constructor(protected readonly service: InvitationService) {}

  async _invitationsMeta(
    @graphql.Args() args: InvitationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Invitation])
  async invitations(
    @graphql.Args() args: InvitationFindManyArgs
  ): Promise<Invitation[]> {
    return this.service.invitations(args);
  }

  @graphql.Query(() => Invitation, { nullable: true })
  async invitation(
    @graphql.Args() args: InvitationFindUniqueArgs
  ): Promise<Invitation | null> {
    const result = await this.service.invitation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Invitation)
  async createInvitation(
    @graphql.Args() args: CreateInvitationArgs
  ): Promise<Invitation> {
    return await this.service.createInvitation({
      ...args,
      data: {
        ...args.data,

        account: args.data.account
          ? {
              connect: args.data.account,
            }
          : undefined,

        invitee: args.data.invitee
          ? {
              connect: args.data.invitee,
            }
          : undefined,

        inviter: {
          connect: args.data.inviter,
        },
      },
    });
  }

  @graphql.Mutation(() => Invitation)
  async updateInvitation(
    @graphql.Args() args: UpdateInvitationArgs
  ): Promise<Invitation | null> {
    try {
      return await this.service.updateInvitation({
        ...args,
        data: {
          ...args.data,

          account: args.data.account
            ? {
                connect: args.data.account,
              }
            : undefined,

          invitee: args.data.invitee
            ? {
                connect: args.data.invitee,
              }
            : undefined,

          inviter: {
            connect: args.data.inviter,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Invitation)
  async deleteInvitation(
    @graphql.Args() args: DeleteInvitationArgs
  ): Promise<Invitation | null> {
    try {
      return await this.service.deleteInvitation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Account, {
    nullable: true,
    name: "account",
  })
  async getAccount(
    @graphql.Parent() parent: Invitation
  ): Promise<Account | null> {
    const result = await this.service.getAccount(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "invitee",
  })
  async getInvitee(@graphql.Parent() parent: Invitation): Promise<User | null> {
    const result = await this.service.getInvitee(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "inviter",
  })
  async getInviter(@graphql.Parent() parent: Invitation): Promise<User | null> {
    const result = await this.service.getInviter(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
