/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TransactionService } from "../transaction.service";
import { TransactionCreateInput } from "./TransactionCreateInput";
import { Transaction } from "./Transaction";
import { TransactionFindManyArgs } from "./TransactionFindManyArgs";
import { TransactionWhereUniqueInput } from "./TransactionWhereUniqueInput";
import { TransactionUpdateInput } from "./TransactionUpdateInput";
import { AttachmentFindManyArgs } from "../../attachment/base/AttachmentFindManyArgs";
import { Attachment } from "../../attachment/base/Attachment";
import { AttachmentWhereUniqueInput } from "../../attachment/base/AttachmentWhereUniqueInput";

export class TransactionControllerBase {
  constructor(protected readonly service: TransactionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Transaction })
  async createTransaction(
    @common.Body() data: TransactionCreateInput
  ): Promise<Transaction> {
    return await this.service.createTransaction({
      data: {
        ...data,

        account: data.account
          ? {
              connect: data.account,
            }
          : undefined,

        aiExtraction: data.aiExtraction
          ? {
              connect: data.aiExtraction,
            }
          : undefined,

        category: data.category
          ? {
              connect: data.category,
            }
          : undefined,

        counterpartyUser: data.counterpartyUser
          ? {
              connect: data.counterpartyUser,
            }
          : undefined,

        recordedBy: {
          connect: data.recordedBy,
        },
      },
      select: {
        account: {
          select: {
            id: true,
          },
        },

        aiExtraction: {
          select: {
            id: true,
          },
        },

        amount: true,

        category: {
          select: {
            id: true,
          },
        },

        counterpartyName: true,

        counterpartyUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        currency: true,
        dateOccurred: true,
        deletedAt: true,
        description: true,
        dueDate: true,
        externalRef: true,
        id: true,
        isRecurring: true,
        meta: true,
        paidAt: true,

        recordedBy: {
          select: {
            id: true,
          },
        },

        recurrenceRule: true,
        status: true,
        title: true,
        type: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Transaction] })
  @ApiNestedQuery(TransactionFindManyArgs)
  async transactions(@common.Req() request: Request): Promise<Transaction[]> {
    const args = plainToClass(TransactionFindManyArgs, request.query);
    return this.service.transactions({
      ...args,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        aiExtraction: {
          select: {
            id: true,
          },
        },

        amount: true,

        category: {
          select: {
            id: true,
          },
        },

        counterpartyName: true,

        counterpartyUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        currency: true,
        dateOccurred: true,
        deletedAt: true,
        description: true,
        dueDate: true,
        externalRef: true,
        id: true,
        isRecurring: true,
        meta: true,
        paidAt: true,

        recordedBy: {
          select: {
            id: true,
          },
        },

        recurrenceRule: true,
        status: true,
        title: true,
        type: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Transaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async transaction(
    @common.Param() params: TransactionWhereUniqueInput
  ): Promise<Transaction | null> {
    const result = await this.service.transaction({
      where: params,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        aiExtraction: {
          select: {
            id: true,
          },
        },

        amount: true,

        category: {
          select: {
            id: true,
          },
        },

        counterpartyName: true,

        counterpartyUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        currency: true,
        dateOccurred: true,
        deletedAt: true,
        description: true,
        dueDate: true,
        externalRef: true,
        id: true,
        isRecurring: true,
        meta: true,
        paidAt: true,

        recordedBy: {
          select: {
            id: true,
          },
        },

        recurrenceRule: true,
        status: true,
        title: true,
        type: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Transaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTransaction(
    @common.Param() params: TransactionWhereUniqueInput,
    @common.Body() data: TransactionUpdateInput
  ): Promise<Transaction | null> {
    try {
      return await this.service.updateTransaction({
        where: params,
        data: {
          ...data,

          account: data.account
            ? {
                connect: data.account,
              }
            : undefined,

          aiExtraction: data.aiExtraction
            ? {
                connect: data.aiExtraction,
              }
            : undefined,

          category: data.category
            ? {
                connect: data.category,
              }
            : undefined,

          counterpartyUser: data.counterpartyUser
            ? {
                connect: data.counterpartyUser,
              }
            : undefined,

          recordedBy: {
            connect: data.recordedBy,
          },
        },
        select: {
          account: {
            select: {
              id: true,
            },
          },

          aiExtraction: {
            select: {
              id: true,
            },
          },

          amount: true,

          category: {
            select: {
              id: true,
            },
          },

          counterpartyName: true,

          counterpartyUser: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          currency: true,
          dateOccurred: true,
          deletedAt: true,
          description: true,
          dueDate: true,
          externalRef: true,
          id: true,
          isRecurring: true,
          meta: true,
          paidAt: true,

          recordedBy: {
            select: {
              id: true,
            },
          },

          recurrenceRule: true,
          status: true,
          title: true,
          type: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Transaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTransaction(
    @common.Param() params: TransactionWhereUniqueInput
  ): Promise<Transaction | null> {
    try {
      return await this.service.deleteTransaction({
        where: params,
        select: {
          account: {
            select: {
              id: true,
            },
          },

          aiExtraction: {
            select: {
              id: true,
            },
          },

          amount: true,

          category: {
            select: {
              id: true,
            },
          },

          counterpartyName: true,

          counterpartyUser: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          currency: true,
          dateOccurred: true,
          deletedAt: true,
          description: true,
          dueDate: true,
          externalRef: true,
          id: true,
          isRecurring: true,
          meta: true,
          paidAt: true,

          recordedBy: {
            select: {
              id: true,
            },
          },

          recurrenceRule: true,
          status: true,
          title: true,
          type: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/attachments")
  @ApiNestedQuery(AttachmentFindManyArgs)
  async findAttachments(
    @common.Req() request: Request,
    @common.Param() params: TransactionWhereUniqueInput
  ): Promise<Attachment[]> {
    const query = plainToClass(AttachmentFindManyArgs, request.query);
    const results = await this.service.findAttachments(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        kind: true,
        mimeType: true,
        sizeBytes: true,

        transaction: {
          select: {
            id: true,
          },
        },

        transcript: true,

        uploadedBy: {
          select: {
            id: true,
          },
        },

        url: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/attachments")
  async connectAttachments(
    @common.Param() params: TransactionWhereUniqueInput,
    @common.Body() body: AttachmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attachments: {
        connect: body,
      },
    };
    await this.service.updateTransaction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/attachments")
  async updateAttachments(
    @common.Param() params: TransactionWhereUniqueInput,
    @common.Body() body: AttachmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attachments: {
        set: body,
      },
    };
    await this.service.updateTransaction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/attachments")
  async disconnectAttachments(
    @common.Param() params: TransactionWhereUniqueInput,
    @common.Body() body: AttachmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attachments: {
        disconnect: body,
      },
    };
    await this.service.updateTransaction({
      where: params,
      data,
      select: { id: true },
    });
  }
}
