/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Transaction } from "./Transaction";
import { TransactionCountArgs } from "./TransactionCountArgs";
import { TransactionFindManyArgs } from "./TransactionFindManyArgs";
import { TransactionFindUniqueArgs } from "./TransactionFindUniqueArgs";
import { CreateTransactionArgs } from "./CreateTransactionArgs";
import { UpdateTransactionArgs } from "./UpdateTransactionArgs";
import { DeleteTransactionArgs } from "./DeleteTransactionArgs";
import { AttachmentFindManyArgs } from "../../attachment/base/AttachmentFindManyArgs";
import { Attachment } from "../../attachment/base/Attachment";
import { Account } from "../../account/base/Account";
import { AiExtraction } from "../../aiExtraction/base/AiExtraction";
import { Category } from "../../category/base/Category";
import { User } from "../../user/base/User";
import { TransactionService } from "../transaction.service";
@graphql.Resolver(() => Transaction)
export class TransactionResolverBase {
  constructor(protected readonly service: TransactionService) {}

  async _transactionsMeta(
    @graphql.Args() args: TransactionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Transaction])
  async transactions(
    @graphql.Args() args: TransactionFindManyArgs
  ): Promise<Transaction[]> {
    return this.service.transactions(args);
  }

  @graphql.Query(() => Transaction, { nullable: true })
  async transaction(
    @graphql.Args() args: TransactionFindUniqueArgs
  ): Promise<Transaction | null> {
    const result = await this.service.transaction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Transaction)
  async createTransaction(
    @graphql.Args() args: CreateTransactionArgs
  ): Promise<Transaction> {
    return await this.service.createTransaction({
      ...args,
      data: {
        ...args.data,

        account: args.data.account
          ? {
              connect: args.data.account,
            }
          : undefined,

        aiExtraction: args.data.aiExtraction
          ? {
              connect: args.data.aiExtraction,
            }
          : undefined,

        category: args.data.category
          ? {
              connect: args.data.category,
            }
          : undefined,

        counterpartyUser: args.data.counterpartyUser
          ? {
              connect: args.data.counterpartyUser,
            }
          : undefined,

        recordedBy: {
          connect: args.data.recordedBy,
        },
      },
    });
  }

  @graphql.Mutation(() => Transaction)
  async updateTransaction(
    @graphql.Args() args: UpdateTransactionArgs
  ): Promise<Transaction | null> {
    try {
      return await this.service.updateTransaction({
        ...args,
        data: {
          ...args.data,

          account: args.data.account
            ? {
                connect: args.data.account,
              }
            : undefined,

          aiExtraction: args.data.aiExtraction
            ? {
                connect: args.data.aiExtraction,
              }
            : undefined,

          category: args.data.category
            ? {
                connect: args.data.category,
              }
            : undefined,

          counterpartyUser: args.data.counterpartyUser
            ? {
                connect: args.data.counterpartyUser,
              }
            : undefined,

          recordedBy: {
            connect: args.data.recordedBy,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Transaction)
  async deleteTransaction(
    @graphql.Args() args: DeleteTransactionArgs
  ): Promise<Transaction | null> {
    try {
      return await this.service.deleteTransaction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Attachment], { name: "attachments" })
  async findAttachments(
    @graphql.Parent() parent: Transaction,
    @graphql.Args() args: AttachmentFindManyArgs
  ): Promise<Attachment[]> {
    const results = await this.service.findAttachments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Account, {
    nullable: true,
    name: "account",
  })
  async getAccount(
    @graphql.Parent() parent: Transaction
  ): Promise<Account | null> {
    const result = await this.service.getAccount(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => AiExtraction, {
    nullable: true,
    name: "aiExtraction",
  })
  async getAiExtraction(
    @graphql.Parent() parent: Transaction
  ): Promise<AiExtraction | null> {
    const result = await this.service.getAiExtraction(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Category, {
    nullable: true,
    name: "category",
  })
  async getCategory(
    @graphql.Parent() parent: Transaction
  ): Promise<Category | null> {
    const result = await this.service.getCategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "counterpartyUser",
  })
  async getCounterpartyUser(
    @graphql.Parent() parent: Transaction
  ): Promise<User | null> {
    const result = await this.service.getCounterpartyUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "recordedBy",
  })
  async getRecordedBy(
    @graphql.Parent() parent: Transaction
  ): Promise<User | null> {
    const result = await this.service.getRecordedBy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
